on:
  workflow_dispatch:
  push:
    branches:
    - main

permissions: read-all

name: test
jobs:
  test:
    runs-on: windows-latest

    steps:
    - run: gh cs list
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}