on:
  workflow_dispatch:
  push:
    branches:
    - main

name: test
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - 'amazon/aws-lambda-dotnet:6'

    container:
      image: ${{ matrix.image }}

    steps:
    -  run: whoami